### ISSUE TITLE
Module 1, Lab2, Task 10, Visual Studio Installation

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-500-Azure-Security#101]
# Module: 01
# Lab 2
#### Step: 1

Description of issue: I never used Visual Studio before. In Lab 2 of Module 1 (task 10), it ask to open Visual Studio 2019. I installed Visual Studio for Community but I can't find Visual C# option in it when creating new project.

Do I have to install Visual Studio Professional or Enterprise? or I need to add extra tools with my raw installation of Visual Studio 2019 community? Thanks

Repro steps:

1.
1.
1.

**Comment by garethjones294** [comment]
Hi

You will need to modify the installation and add the additional components.

More info is available here: https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019

Regards
