### ISSUE TITLE
"Get entities" missing

### ISSUE THREAD

**Issue by simplescripter** [MicrosoftLearning/AZ-500-Azure-Security#106]
# Module: 04
#### Step: 09 and 10

Description of issue

Instructions state to "Use Get entities functions," but I can't find any reference to "Get entities" in Azure Sentinel. And in Step 10, the screenshot doesn't resolve to an image: 

![image](https://user-images.githubusercontent.com/37522686/80651307-ebf63300-8a32-11ea-9b5d-360ea5b2fcb6.png)

Repro steps:

1.
1.
1.

**Comment by garethjones294** [comment]
Hi, I have now amended the screenshot to the entities piece should make more sense in the Logic App.
