### ISSUE TITLE
Module 2: Lab 18 - Custom Domains

### ISSUE THREAD

**Issue by AlexW134** [MicrosoftLearning/AZ-500-Azure-Security#110]
# Module: 02
#### Step: 00

This lab mentions using godeploy DNS which LOD and other providers do not have access to.

Not sure if the steps can be revamped to use a common DNS or eliminate this lab if not using godeploy as Lab provider.

**Comment by garethjones294** [comment]
Hi,

We are hoping other lab providers will add this functionality into their environments to enable this lab to be completed.
