### ISSUE TITLE
Module 2 LAb 12 - Firewall - doesn't work

### ISSUE THREAD

**Issue by deraeler** [MicrosoftLearning/AZ-500-Azure-Security#111]
# Module: 02
#### Step: TESTING upon completion

Description of issue

Repro steps:

1.Do all lab steps
2.TEST
3.FAIL.  msn.com cannot be reached. Nor can any other web site entered as an App rule on the firewall.  Giant waste of many hours.

**Comment by garethjones294** [comment]
I have tested this twice, both myself and with another MCT and both times the lab was successful.

**Comment by deraeler** [comment]
I appreciate your looking into this. I've been over and over this config -
what am I missing?

The DNS definitions appear to be valid, the Jump server can resolve the
same domains (msn.com etc), using the same DNS servers.
However although the DNS definitions appear in an NSLOOKUP from the Work
server, it simply won't resolve msn.com (I added additional rule for
Yahoo.com etc., but it wont resolve those either).
From the local (Work) server, I verified Windows firewall is allowing all
outbound traffic.

I cant re-verify today as my subscription is cancelled (tried submitting a
support request, but they require a page trace, which also doesn't work,
and the support page is no longer supported - of course).
These learning subscriptions are apparently yanked before they're expired,
another Microsoft lie.

Well in hopes that I've located an engineer with some integrity still at
Microsoft perhaps you can help me salvage some education from the $2000+
I've spent on this course.



[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]


[image: image.png]

**Comment by deraeler** [comment]
I've provided documented proof of identical config here to the Lab instructions.  Just closing the issue doesn't explain why it's not working.  I can fire off a one-liner stating it works for me too - but that doesn't prove anything nor help anyone. Do the courtesy of at least looking at what I've provided, I invested a lot of hours in YOUR lab, with nothing to show for it.
