### ISSUE TITLE
Incorrect steps on Module 1 / Lab 1 / Exercise 5 (updated GUI)

### ISSUE THREAD

**Issue by Valtiter** [MicrosoftLearning/AZ-500-Azure-Security#112]
# Module: 1
#### Step: several

> Description of issue: Some steps are incorrect, the GUI was updated recently.
> Below, you can see the correct steps for the task 1 and part of task 2.
> The images in the tasks and the remaining steps of task 2 (from 6 to 11) are correct.

**Exercise 5 - PIM Resource Workflows**

**Task 1: Configure the Global Administrator role to require approval.**

1. Open  **Azure AD Privileged Identity Management**.
2. Click **Azure AD Roles.**
3. Click **Roles** and select **Global Administrator.**
4. Click on **Role settings.**
5. In the **Role setting** blade, click on **Edit.**
6. Scroll down and select  **Require approval to activate**  and select your account as the approver then click  **Select.**
7. In the **Edit role setting – Global Administrator** blade, click  **Update.**

![](RackMultipart20200503-4-145jvlz_html_6b7dd6c95316b34c.png)

**Task 2: Enable Isabella for Global Administrator privileges.**

1. Open  **Azure AD Privileged Identity Management**.
2. Click  **Azure AD roles**.
3. Click the  **Quick Start**  and select  **Assign eligibility**.
4. Select  **Global Administrator** and click **+Add assignments.**
5. In the **Add assignments** blade, under **Select member(s) \*** click **No member selected** ,select  **Isabella**  and click  **Select**  then click  **Nex** t and then **Assign**.

**Comment by garethjones294** [comment]
Lab tested and updated.

**Comment by Valtiter** [comment]
At the end of the task 1 there was the following image that is still valid and useful. It could be possible to restore that?

![lab1-1](https://user-images.githubusercontent.com/28950560/80916302-1e1bd380-8d58-11ea-8b99-508566f0be7b.png)

**Comment by garethjones294** [comment]
Added image
