### ISSUE TITLE
Wrong Image

### ISSUE THREAD

**Issue by Valtiter** [MicrosoftLearning/AZ-500-Azure-Security#114]
# Module: 2
#### Step: 2

Description of issue: There is a wrong image (it's referred to the last step of the lab), please correct.

**Comment by garethjones294** [comment]
Completed lab and the last few screenshots of the lab are correct

**Comment by Valtiter** [comment]
There is the same image in two different points of the document: in Module 2, Lab 10, Exercise 2, Task 1, Step 2 is wrong;  in Module 2, Lab 10, Exercise 3, Task 2, step 2 is correct.
Please remove or correct the first occurrence with the following image:

![Correct](https://user-images.githubusercontent.com/28950560/81169024-6590a280-8f98-11ea-8688-c4bb5f4fc479.PNG)

**Comment by garethjones294** [comment]
Fixed
