### ISSUE TITLE
Lab 11 -Template availability

### ISSUE THREAD

**Issue by staleycyn** [MicrosoftLearning/AZ-500-Azure-Security#115]
# Module: 02
#### Step: 01

The template will not deploy. Here is the error. Looks like this might have been taken out of market. 

{

    "error": {
        "code": "MarketplacePurchaseEligibilityFailed",
        "message": "Marketplace purchase eligibilty check returned errors. See inner errors for details. ",

        "details": [
            {
                "code": "BadRequest",
                "message": "Offer with PublisherId: sophos, OfferId: sophos-xg cannot be purchased due to validation errors. See details for more information.[{\"Offer with PublisherId: sophos, OfferId: sophos-xg, PlanId: byol can not be purchased by subscriptionId: f32cbc6a-b0e6-40f0-950d-13f9fa0df76b. The publisher has decided not to make this offer available for purchase.\":\"StoreApi\"}]"
            }
        ]
    }
}

**Comment by garethjones294** [comment]
Hi, 

Sophos are aware of this issue and working on a resolution.

Regards
