### ISSUE TITLE
Module_1: LAB_02_Key_Vault.md: Minor UI Issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#120]
LAB_02_Key_Vault.md: Minor UI Issues:
--
Ex 1   Task 2 Step 2: If prompted for "more information" can enable MFA or click "Skip for Now" and authenticate again.
Ex 1   Task 2 Step 4: Ignore warnings.
Ex 1   Task 2 Step 6: "Click on the KeyVaultPS to examine what you have   created." should be "Click on the Key Vault name to examine what you have created. Note: For all future instructions replace KeyVaultPS with the name of your Key Vault."
Ex 1   Task 2 Step 10: If Access Policy already exists then Save will be grayed out.
Ex 1   Task 10 Step 3: "Visual C#" should be "C#"
Ex 1   Task 10 Step 3: "click OK." should be "click Create"
Ex 1   Task 10 Step 13: Ignore Intellisense errors.

**Comment by garethjones294** [comment]
Ex 1 Task 2 Step 2: If prompted for "more information" can enable MFA or click "Skip for Now" and authenticate again.  **MFA has not been enabled at this stage.  There was an issue with some Azure Accounts being prompted but does not justify a change.**
Ex 1 Task 2 Step 4: Ignore warnings.  **Not Applicable.**
Ex 1 Task 2 Step 6: "Click on the KeyVaultPS to examine what you have created." should be "Click on the Key Vault name to examine what you have created. Note: For all future instructions replace KeyVaultPS with the name of your Key Vault."  **Changed**
Ex 1 Task 2 Step 10: If Access Policy already exists then Save will be grayed out.  **No access policy should exist.**
Ex 1 Task 10 Step 3: "Visual C#" should be "C#"  **Changed**
Ex 1 Task 10 Step 3: "click OK." should be "click Create"  **Changed**
Ex 1 Task 10 Step 13: Ignore Intellisense errors. **Could not reproduce.**
