### ISSUE TITLE
Module_2: LAB_01_Monitor & Autoscale.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#125]
Module_2: LAB_01_Monitor & Autoscale.md: Minor UI issues:
--
Ex 2   Step 5: "UX recommends" should be "UI recommends"
Ex 2   Step 7: If you receive an error "Microsoft.insights not registered"   (Add button grayed out) go to your Subscription blade and under Resource   Providers register "Microsoft.insights" and wait a few minutes for   registration then retry. If it does not register, continue at Task 2.

**Comment by garethjones294** [comment]
Ex 2 Step 5: "UX recommends" should be "UI recommends"  **Same thing but amended**
Ex 2 Step 7: If you receive an error "Microsoft.insights not registered" (Add button grayed out) go to your Subscription blade and under Resource Providers register "Microsoft.insights" and wait a few minutes for registration then retry. If it does not register, continue at Task 2.  **Added**
