### ISSUE TITLE
Module_2: LAB_02_Function Apps.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#126]
Module_2: LAB_02_Function Apps.md: Minor UI issues: 
--
Ex 1   Task 1 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.
Ex 1   Task 3 Step 4: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.
Ex 1   Task 3 Step 4: Click the Raw button then Ctrl+A and Ctrl+C to copy all the Powershell code.
Ex 1   Task 3 Step 5: If the Script pane is not open, select View/Show Script Pane.

**Comment by garethjones294** [comment]
Ex 1 Task 1 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.  **Correctly formatted in GitHub & Markdown**
Ex 1 Task 3 Step 4: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code. **Correctly formatted in GitHub & Markdown**
Ex 1 Task 3 Step 4: Click the Raw button then Ctrl+A and Ctrl+C to copy all the Powershell code.  **Amended so its raw.**
Ex 1 Task 3 Step 5: If the Script pane is not open, select View/Show Script Pane. **Added**
