### ISSUE TITLE
Module_2: LAB_03_Create a Kubernetes Cluster.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#127]
Module_2: LAB_03_Create a Kubernetes Cluster.md: Minor UI issues:
--
Ex 1   Task 1 Step 4: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.
Ex 1   Task 2 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.
Ex 1   Task 3 Step 2: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.  
Ex 1   Task 4 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.
Ex 1   Task 5 Step 1: CLI code does not render correctly in LODS from GitHub. Error.   Please remove indentation of code.
Ex 1   Task 6 Step 7: Click the vote buttons in the application (Cats/Dogs) then   view the live data under the Logs window.
Ex 1   Task 7 Step 1: "Run the following command to delete the cluster."   should be "Run the following command in Cloudshell to delete the cluster."
Ex 1   Task 7 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.

**Comment by garethjones294** [comment]
Ex 1 Task 1 Step 4: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.  **Removed CLI and added BASH**
Ex 1 Task 2 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code.  **Removed CLI and added BASH**
Ex 1 Task 3 Step 2: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code. **Removed CLI and added BASH**
Ex 1 Task 4 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code. **Removed CLI and added BASH**
Ex 1 Task 5 Step 1: CLI code does not render correctly in LODS from GitHub. Error. Please remove indentation of code. **Removed CLI and added BASH**
Ex 1 Task 6 Step 7: Click the vote buttons in the application (Cats/Dogs) then view the live data under the Logs window.  **Reworded**
Ex 1 Task 7 Step 1: "Run the following command to delete the cluster." should be "Run the following command in Cloudshell to delete the cluster." **Reworded**
Ex 1 Task 7 Step 1: CLI code does not render correctly in LODS from GitHub. Please remove indentation of code. **Removed CLI and added BASH**
