### ISSUE TITLE
Module 1: Lab 6: Manage Identity and Access

### ISSUE THREAD

**Issue by gro1m** [MicrosoftLearning/AZ-500-Azure-Security#128]
# Module: 01
#### Step: 08

Description of issue
Needs `Connect-AzureAD` before 
```bash
New-AzureADUser -DisplayName "Mark" -PasswordProfile $PasswordProfile     -UserPrincipalName "Mark@leachimgross2outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Mark"
```

Otherwise you get the following error/warning:
You must call the Connect-AzureAD cmdlet before calling any other cmdlets.

**Comment by garethjones294** [comment]
Already added.
