### ISSUE TITLE
Module 2: Lab 15 - Manage Azure DDoS Protection Standard

### ISSUE THREAD

**Issue by SethJanssen** [MicrosoftLearning/AZ-500-Azure-Security#129]
# Module: 02
#### Step: 04

No step in the lab before this explicitly says to make a public IP address before this point. Not really an issue in my opinion, but worth noting.

Step 4 is trying to have you make an alert that emails you, but the step doesn't reflect the current state of the portal. It has you go to Monitor then Metrics to make the alert, but doesn't give any details on how to do this. You can make an alert there, but it's more complicated than what the step describes.

### Task: 06 and 07

The steps don't reflect how the portal currently looks. Fairly minor problem as all of the options are still there to select.

**Comment by garethjones294** [comment]
Updated the lab to incorporate portal changes and give more clarity for Azure Monitor.
