### ISSUE TITLE
Template file is not same as hands on labs , it is not creating sophosX Firewall

### ISSUE THREAD

**Issue by dipankar98228** [MicrosoftLearning/AZ-500-Azure-Security#13]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by kramit** [comment]
can you give details on this? What steps have you taken so we can reproduce the error to troubleshoot

**Comment by garethjones294** [comment]
Link fixed

**Comment by dipankar98228** [comment]
cheers !!
