### ISSUE TITLE
AZ-500 Labs general: Fenced code blocks issue

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#130]
From GitHub Flavored Markdown: https://github.github.com/gfm/#fenced-code-blocks
"A fenced code block begins with a code fence, indented no more than three spaces."

Is it possible to remove the indentation of these fenced code blocks? Most of them are indented 5 spaces. This is causing problems when importing the instructions.

See example screenshot.
![Screenshot (5127)](https://user-images.githubusercontent.com/22414394/81510683-a6aeec80-92e1-11ea-9bd1-43ba39a10e9c.png)

**Comment by garethjones294** [comment]
Hi

Please submit a pull request for review.  At present the markdown is formatted correctly in GitHub so this will need to be reviewed.

Regards
