### ISSUE TITLE
Module_1: LAB_03_MFA.md: Done button has returned

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#131]
Module_1: LAB_03_MFA.md: Done button has returned:
--
Sorry, The Done buttons that disappeared last week have now returned. Apologies!

Ex 1   Task 1 Step 10d: add "On the Users and groups page, click Done."
Ex 1   Task 1 Step 12d: add "On the Cloud apps page, click Done."
Ex 2 Task 1 Step 8: add   "click Done."
Ex 2 Task 1 Step 9: add   "click Done."

**Comment by garethjones294** [comment]
Amended
