### ISSUE TITLE
Cost Management + Billing | Subscription not accessible for Azure Pass-Sponsorship subscription

### ISSUE THREAD

**Issue by gro1m** [MicrosoftLearning/AZ-500-Azure-Security#133]
# Module: 01
#### Step: 02

Description of issue
According to https://github.com/MicrosoftLearning/AZ-500-Azure-Security/blob/master/Instructions/Labs/Module_1/LAB_09_Subscriptions.md Azure Pass-Sponsorhip cannot yet use the Cost Management blade. Problem is you do not see Subscription menu and therefore can also not do anything such like managing Subscriptions.

Repro steps:
1. Login with Azure Pass - Sponsorship Subscription, you do not see the Subscription menu in the left pane.

**Comment by garethjones294** [comment]
Subscriptions are working:

![image](https://user-images.githubusercontent.com/25365143/82043222-20a8f200-96a3-11ea-96e0-ea927634e10d.png)

**Comment by gro1m** [comment]
It is working if you enable preview feature, but the documentation of the lab states:
Note: At the time of writing, Azure Pass - Sponsorship subscriptions are not eligible for transfer. Follow this guide through for reference.
