### ISSUE TITLE
Module_2/LAB_01_Monitor & Autoscale.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#134]
Module_2/LAB_01_Monitor & Autoscale.md: Minor UI changes:
--

Ex 2   Step 7: "If it does not register, continue at Task 2." should   be  "If it does not register,   continue at next excercise."

Ex 4   Step 4: Click Save.

**Comment by garethjones294** [comment]
Amended
