### ISSUE TITLE
Module_2/LAB_02_Function Apps.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#135]
Module_2/LAB_02_Function Apps.md: Minor UI changes:
--

Ex 1   Task 2 Step 3: "assgined " should be "assigned "
Ex 1   Task 2 Step 4: Click on the word "Functions" (not the "+" button)
Ex 1   Task 3 Step 4: Click Ctrl+A and Ctrl+C to copy all the Powershell code.

**Comment by garethjones294** [comment]
Made amendments and added screenshots for clarity

How to copy and paste code should not be required on a level 300 course.  Students can copy paste any way they see fit.
