### ISSUE TITLE
Module_2/LAB_03_Create a Kubernetes Cluster.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#136]
Module_2/LAB_03_Create a Kubernetes Cluster.md: Minor UI changes:
--
Ex 1   Task 1 Step 4: May have to wait for previous myResourceGroup to be deleted if   you used the same name. Choose a different resource group name if necessary.
Ex 1   Task 6 Step 7: Click view live data then click the vote buttons in the running application   (Cats/Dogs) then view the live data under the Logs window.
Ex 1   Task 7 Step 1: "Run the following command to delete the cluster."   should be "Run the following command in Cloudshell to delete the   resource group. Note this may take several minutes."
Ex 1   Task 7 Step 1: It may take many minutes to delete the resource group (the nowait option runs the delete in the   background)

**Comment by garethjones294** [comment]
Changed RG name to stop issues

Made other amendments
