### ISSUE TITLE
Module_3/LAB_01_Classify a SQL Database.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#137]
Module_3/LAB_01_Classify a SQL Database.md: Minor UI issues:
--
Ex 1   Task 1 Step 7: "az500labserver" should be "the unique server name you provided earlier. (all future instructions will reference az500labserver as the server name)
Ex 1   Task 1 Step 20: If error after save (container not created), then close   portal (discard changes), reopen portal. Make sure storage account was   created, then reopen SQL database blade and open Advanced Data Security page   again and try to configure storage again this time adding existing storage   account from list and save.
Ex 2   Step 3: Click banner at bottom to view 15 columns.
Ex 2   Step 4: Use default AddressID   column with Information type Other and Sensitivity General.

**Comment by garethjones294** [comment]
Made amendments

Ex 1 Task 1 Step 20: If error after save (container not created), then close portal (discard changes), reopen portal. Make sure storage account was created, then reopen SQL database blade and open Advanced Data Security page again and try to configure storage again this time adding existing storage account from list and save.  **Could not reproduce this issue.**
