### ISSUE TITLE
Module_3/LAB_02_Auditing a Database.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#138]
Module_3/LAB_02_Auditing a Database.md: Minor UI issues:
--
Ex 1   Task 2 Step 2: "az500labserver2" should be "the unique server   name you provided earlier. (all future instructions will reference az500labserver2 as the server name)
Ex 1   Task 2 Step 8: "Click Create New" should be "Click Storage   account, then if necessary click Create New. The Create storage account blade   should open."
Ex 2   Task 1 Step 1: May have to click Refresh to see the new database.

**Comment by garethjones294** [comment]
Amendments made
