### ISSUE TITLE
Module_3/LAB_03_Analyze audit logs and reports.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#139]
Module_3/LAB_03_Analyze audit logs and reports.md: Minor UI issues:
--
Ex 1   Task 0 Step 3: "You can use the default populated SQL server name"   should be "You can use the default populated SQL server name with a   unique string added to make a globaly unique name."
Ex 1   Task 1 Step 10: "e.g. Mod3Lab3YOURNAME" should be "e.g.   mod3lab3yourname"
Ex 1   Task 1 after Step 18 below PowerShell commands: Return to Advanced Data   Security blade in portal. (Note Event Hub Namespace will be a unique name you   specified).
Ex 1   Task 2 Step 2: Event data not populated in demo site.
Ex 1   Task 2 Step 4: Event data not populated in demo site.

**Comment by garethjones294** [comment]
Amendments made
