### ISSUE TITLE
Template in this hands on is of Lab 12 

### ISSUE THREAD

**Issue by dipankar98228** [MicrosoftLearning/AZ-500-Azure-Security#14]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by kramit** [comment]
can you give details on this? What steps have you taken so we can reproduce the error to troubleshoot

**Comment by dipankar98228** [comment]
change the lab template of lab 11 to lab 12 template

**Comment by garethjones294** [comment]
Hi, could you please provide detailed information.  This does not make sense and the labs are currently functioning as expected.

**Comment by dipankar98228** [comment]
hi, Module 2 lab 11.. json template is deploying resource which are going to be used in Module 2 Lab 12.

**Comment by garethjones294** [comment]
Link fixed
