### ISSUE TITLE
Module_4/LAB_01_Azure Monitor.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#140]
Module_4/LAB_01_Azure Monitor.md: Minor UI issues:
--
Ex 1   Task 2 Step 1: "In the Azure portal, select All services." should   be "In the Azure portal, select Create a resource."
Ex 1   Task 2 Step 3: "select OK. " should be "select Review+Create then select Create."
Ex 1   Task 4 Step 2: May have to wait several minutes for performance counters to   appear in results.
Ex 2   Task 1 Step 1: "Management tools" should be "IT & Management tools"
Ex 2   Task 1 Step 2: "Click Add." should be "select Review+Create then select Create."
Ex 1   Task 3 Step 1: Navigate to the Applications Insights blade first.
Ex 1   Task 3 Step 2: Make sure you save the file.
Ex 1   Task 4 Step 2: Then click Run.
Ex 1   Task 4 Step 3: Change Local Time   button from Last 24 hours to Last 30 Minutes. Change Server/Browser button to Browser.

**Comment by garethjones294** [comment]
Amendments made and screenshots updated
