### ISSUE TITLE
Module_4/LAB_02_Security Center.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#141]
Module_4/LAB_02_Security Center.md: Minor UI issues:
--
Ex 1   Task 1 Step 6: "otherwise the following exercises will function as   expected." should be "otherwise the following exercises will not function as expected."
Ex 2   Task 1 Step 6: "VMs and Computers." should be "VMs and Servers."

**Comment by garethjones294** [comment]
Amendments made updated screenshots
