### ISSUE TITLE
Module_4/LAB_03_Event Hub.md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#142]
Module_4/LAB_03_Event Hub.md: Minor UI issues:
--
Ex 1   Task 1 Step 3: "Click Create. " should be "Select   Review+Create then select Create."
Ex 1   Task 2 Step 13: "Click OK" should be "Click Create"
Ex 1   Task 5 Step 1: "icaon" should be "icon"
Ex 1   Task 5 Step 7: "Click Blobs" should be "Click Containers"

**Comment by garethjones294** [comment]
Amendments made
