### ISSUE TITLE
Module_2/LAB_03_Create a Kubernetes Cluster.md: Correction

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#143]
Module_2/LAB_03_Create a Kubernetes Cluster.md: Correction:
--
Ex 1   Task 6 Step 7: Should be "Click **view live data** then click the vote buttons in the running application   (Cats/Dogs) then view the live data under the Logs window."

**Comment by garethjones294** [comment]
Amendment made previously
