### ISSUE TITLE
Module 4 Lab 6

### ISSUE THREAD

**Issue by SethJanssen** [MicrosoftLearning/AZ-500-Azure-Security#144]
# Module: 04
##### Step: 09-10
Last two steps are vague.

#### Task: 02
Did not see anything on the Incidents page and didn't have the View full details option. Could be due to inexperience making security playbooks on my part.

#### Task: 01
Task 1 doesn't match the current portal.

**Comment by garethjones294** [comment]
Hi

I have updated aspects of the lab to reflect changes in the Portal.

Regards
