### ISSUE TITLE
Module_2/LAB_03_Create a Kubernetes Cluster.md: Correction

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#147]
Module_2/LAB_03_Create a Kubernetes Cluster.md: Correction:
--
Ex 1 Task 6 Step 7: The whole step should be replaced with the following: "Click the **view live data** button then switch to the running application (Cats/Dogs) to click the vote buttons then switch back to view the live data under the Logs window."

**Comment by garethjones294** [comment]
Amended
