### ISSUE TITLE
Module_2/LAB_04_Create a VNet.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#148]
Module_2/LAB_04_Create a VNet.md: Minor UI changes:
--
Ex 1   Task 2 Step 1: "Select Create a resource > Compute > Windows   Server 2019 Datacenter." should be "Select Create a resource >   Compute > Virtual Machine."
Ex 1   Task 1 Step 2: The UI has changed. Address space and Subnet details are   specified under the IP Addresses   tab.
Ex 1   Task 1 Step 3: "Click Create" should be "Click Review+Create, then click Create"
Ex 1   Task 2 Step 1: "Select Create a resource > Compute > Windows   Server 2019 Datacenter." should be "Select Create a resource >   Compute > Virtual Machine."

**Comment by garethjones294** [comment]
Amendments made
