### ISSUE TITLE
Module_2/LAB_07_Service Endpoints.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#151]
Module_2/LAB_07_Service Endpoints.md: Minor UI changes:
--
Ex 1   Task 1 Step 3: The UI has changed. Address space and Subnet details are   specified under the IP Addresses   tab. Select the existing default subnet to change the name to Public then select Save.
Ex 1   Task 1 Step 3: "Click Create" should be "Click Review+Create, then click Create"
Ex 1   Task 3 Step 3: "Click Create" should be "Click Review+Create, then click Create"
Ex 1   Task 4 Step 3: "Click Create" should be "Click Review+Create, then click Create"
Ex 1   Task 8 Step 1: "Once the myVmPrivate VM finishes creating, Azure opens   the settings for it." should be "Once the myVmPrivate VM finishes   creating, open the blade for the VM by selecting Go to   resource."
Ex 1   Task 8 Step 1: "by selecting the Connect button" should be "by   selecting the Connect button,   then selecting RDP"
Ex 1   Task 8 Step 2: "After selecting the Connect button" should be   "After selecting the Download RDP File button"

**Comment by garethjones294** [comment]
Amendments made
