### ISSUE TITLE
Module_2/LAB_08_VNet Peering.md: Minor UI Changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#152]
Module_2/LAB_08_VNet Peering.md: Minor UI Changes:
--
Ex 1   Task 1 Step 3: The UI has changed. Address space and Subnet details are   specified under the IP Addresses   tab. Select the existing default subnet to change the name to Subnet1 then select Save.
Ex 1   Task 1 Step 3: "Click Create" should be "Click Review+Create, then click Create"
Ex 1   Task 3 Step 2: "Select Create a resource > Compute > Windows   Server 2016 Datacenter." should be "Select Create a resource >   Compute > Virtual Machine."
Ex 1   Task 4 Step 2: "by selecting Connect" should be "by selecting Connect, then selecting RDP, then selecting the Download RDP File button"
Ex 1   Task 4 Step 7: If prompted, enter credentials. If you are able to connect   this proves that you can use the peering connection to myVM2 using RDP on the   internal network.
Ex 1   Task 4 Step 8: If you are able to connect this proves that you can use the   peering connection back to myVM1 using Ping/ICMP on the internal network.

**Comment by garethjones294** [comment]
Amendments made
