### ISSUE TITLE
Module_2/LAB_10_Load Balancer and App Gateway.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#154]
Module_2/LAB_10_Load Balancer and App Gateway.md: Minor UI changes:
--
Ex 1   Task 2 Step 2: The UI has changed. Address space and Subnet details are   specified under the IP Addresses   tab. Select the existing default subnet to change the name to BackendSubnet then select Save.
Ex 1   Task 2 Step 2: "Click Create" should be "Click Review+Create, then click Create"
Ex 3   Task 1 Step 17: "select Create new" should be "select Add new"
Ex 3   Task 1 Step 20: "Select Next: Tags and then Next: Review + create."   should be "Select Next: Tags and then Next: Review + create, then select Create. Wait for the App Gateway to be deployed."
Ex 3   Task 2 Step 2: At end, to verify, go to Network Watcher, choose Topology then choose myResourceGroupLB to see the overall network diagram.

**Comment by garethjones294** [comment]
Amendments made
