### ISSUE TITLE
Module_2/LAB_11_VPN Gateways and Tunnelling.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#155]
Module_2/LAB_11_VPN Gateways and Tunnelling.md: Minor UI changes:
--
(This   lab does not work correctly but shows the steps for setup)
Ex 1   Task 2 Step 2: The UI has changed. Address space and Subnet details are   specified under the IP Addresses   tab. Select the existing Address space then change   according to instructions. Select the Add subnet option to enter the name default then the subnet range according to instructions then select Save.
Note:   there are two Task 2's in Ex 1.
Ex 1   Task 3 Step 6: Select Details   then Go to web page (not recommended)
Ex 1   Task 3 Step 13: "Go to VPN > IPsec Connections, select **Add **and   configure the following settings:" should be "Go to VPN > IPsec   Connections, select Add and   configure the following settings:"
Ex 1   Task 3 Step 13: "Gateway Settings Section: Listening Interface: Leave   the default." should be "Gateway Settings Section: Listening   Interface: Select the default."
Ex 1   Task 3 Step 13: If in doubt, see screenshots in instructions.
Ex 1   Task 4 Step 12: If it does not connect, go back and check settings. If still   no connection, proceed to next lab after deleting resource group.

**Comment by garethjones294** [comment]
Added additional notes and how to force the connection to be established.
