### ISSUE TITLE
Module_2/LAB_12_Azure Firewall.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#156]
Module_2/LAB_12_Azure Firewall.md: Minor UI changes:
--
(This   lab does not work correctly but shows the steps for setup)
Ex 1   Task 2 Step 1: "In the Azure portal, click All services and search for   and select Azure Firewall." should be "In the Azure portal, click Create a resource and search for and   select Firewall."
Ex 1   Task 2 Step 2: "On the Firewall blade click Create firewall. "   should be "On the Firewall   blade click Create.   "
Ex 1   Task 2 Step 3: "Public IP address: Create new" should be   "Public IP address: Add new"
Ex 1   Task 6 Steps 3 and 4 should be Steps A and B indented under step 2.
Ex 1   Task 6 Step 7: Wait for Save to complete.
Ex 1   Task 7 Step 5: Firewall does not block traffic correctly.
Ex 1   Task 7 Step 5: At end, to troubleshoot, go to Network   Watcher, choose Topology then choose TEST-FW-RG to see the overall network diagram.
Ex 1   Task 7 Step 6: The resources created in this lab are NOT needed for the next   lab so delete the resource group TEST-FW-RG.

**Comment by garethjones294** [comment]
Amendments made
