### ISSUE TITLE
Module_2/LAB_13_Secure Admin Access.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#157]
Module_2/LAB_13_Secure Admin Access.md: Minor UI changes:
--
Ex 1   Task 1 Step 2: "Download and install the Putty Installer." should   be "Download and install the Putty Installer 64-bit   (this includes PuttyGen utility" (screenshot needs to be updated)
Ex 1   Task 1 Step 9: (highlight and copy ALL the public key characters including   the ssh-rsa characters at the   top)
Ex 1   Task 3 Step 2: If Public IP is not displayed on the Overview page try to   refresh the browser. Alternatively, try the Networking page and copy the NIC   Public IP which is the same.
Ex 1   Task 3 Step 8: Enter Passphrase Pa55w.rd1234 entered earlier. Note that the   cursor will not move as you type. Press enter key at end.
Ex 1   Task 3 Step 9: The resources created in this lab are NOT needed for the next   lab so delete the resource group myResourceGroup.

**Comment by garethjones294** [comment]
Both versions 32 & 64 include the PuttyGen utility

The screenshots highlight what to copy and students should know how to copy and paste,

Other amendments made.
