### ISSUE TITLE
Module_2/LAB_14_Azure Bastion.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#158]
Module_2/LAB_14_Azure Bastion.md: Minor UI changes:
--
Ex 1   Task 1 Step 1: Open the Azure Portal at https://portal.azure.com first
Ex 1   Task 1 Step 1: If the Cloudshell launches Bash, switch to Powershell by   selecting using the drop down.
Ex 1   Task 1 Step 2: May have to wait for previous myResourceGroup to be deleted if   you used the same name. You can create a different resource group called   myResourceGroup14 if you want to proceed immediately.
Ex 1   Task 1 Step 2: For New-AzVM   command, omit the code   on the end -OpenPorts 80,3389 (otherwise it will create a PublicIP and open ports 80, 3389   for the VM which is not needed for Bastion)
Ex1 Task   1 Step 5: Verify that Subnet is set to AzureBastionSubnet
Ex 1   Task 3 Step 1: "In the Azure portal - Bastion Preview, navigate to your   virtual machine, then click Connect." should be "In the Azure   portal, navigate to your virtual machine, then select Connect."
Ex 1   Task 3 Step 2: "On the right sidebar, click Bastion, then Use   Bastion." should be "Click Bastion" (remove screenshot)

**Comment by garethjones294** [comment]
Amendments made
