### ISSUE TITLE
Module_2/LAB_15_DDoS Protection.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#159]
Module_2/LAB_15_DDoS Protection.md: Minor UI changes:
--
Ex 1   Task 1 Step 3: "Select Create DDos protection plan" should be   "Select Create"
Ex 1   Task 1 Step 4: May have to wait for previous myResourceGroup to be deleted if   you used the same name. You can create a different resource group called   myResourceGroup15 if you want to proceed immediately.
Ex 1   Task 1 Step 3: "Click Create" should be "Click Review+Create, then click Create"
Ex 1   Task 2 Step 3: The UI has changed. DDos details are specified under the Security tab.
Ex 1   Task 5 Step 3: "Select Metrics under SHARED SERVICES." should be   "Select Metrics."
Ex 1   Task 5 Step 4: "On the Monitor blade click Alerts then click + New alert   rule." should be "On the Monitor blade, click +   New alert rule."
Ex 1   Task 5 Step 6: "Select your Subscription and then in the Filter by   resource type drop down" should be "Select your Subscription and   then in the Filter by resource type drop down, select Public   IP addresses then"
Ex 1   Task 5 Step 12: As long as Alert Rule has been successfully created, ignore   the message to discard unsaved changes.
Ex 1   Task 6 Step 3: "Select Metrics under SHARED SERVICES." should be   "Select Metrics."
Ex 1   Task 6 Step 4: then click Apply
Ex 1   Task 6 Step 5: Ignore this step
Ex 1   Task 8 Step 6: "Select Turn on diagnostics to collect the   DDoSMitigationReports log" should be "Select + Add diagnostic setting to collect the DDoSMitigationReports log and name the Diagnostic setting DDoSLog"
Ex 1   Task 8 Step 6: Remember to click Save.

**Comment by garethjones294** [comment]
Amendmenets made
