### ISSUE TITLE
Module_2/LAB_17_Update Management.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#160]
Module_2/LAB_17_Update Management.md: Minor UI changes:
--
Ex 1   Task 1 Step 4: add "then Click Review+Create, then click Create"
Ex 1   Task 6 Step 5: "Click Add Condition" should be "Click Select condition"
Ex 1   Task 6 Step 7: "Click the Select * checkbox next to Runbook name and   Status" should be "Click the Select * checkbox next to Update Deployment   Name and Status"
Ex 1   Task 6 Step 12: "Under Action groups select Create" should be   "Under Action groups click Select action group then click Create action group"
Ex 1   Task 6 Step 16: "Click Add under Action Groups" should be   "Click OK under Create   Action Group"
Ex 1   Task 16 Step 17: "Select your action group and click Select" should   be "Verify your action group is listed"

**Comment by garethjones294** [comment]
Amendments made
