### ISSUE TITLE
Module_2/LAB_19_Private DNS.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#161]
Module_2/LAB_19_Private DNS.md: Minor UI changes:
--
Ex 1   Task 2 Step 5: "select Create" should be "select Review+Create, then select Create"
Ex 1   Task 5 Step 4: Make sure you enter the VM Private IP   address e.g. 10.0.0.4

**Comment by garethjones294** [comment]
Amended
