### ISSUE TITLE
Labs/Module_2/LAB_06_NVA.md: Formatting issue

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#163]
Labs/Module_2/LAB_06_NVA.md: Formatting issue:
--
Ex 1   Task 8 Step 1: Under PUBLIC VM, NETWORKING heading should not be in bold to be consistent with the rest of the table.
Ex   1   Task 8 Step 1: Under Select inbound   ports, "Basic tab" should be "Basics tab" (sorry, my bad from previous update)

**Comment by garethjones294** [comment]
Amendments made
