### ISSUE TITLE
Module_2/LAB_07_Service Endpoints.md: Minor changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#164]
Module_2/LAB_07_Service Endpoints.md: Minor changes:
--
Ex 1   Task 8 Step 1: Double-quote character should be a period at end of step.
Ex 1   Task 8 Step 2: Replace whole step with "Select the **Download RDP File** button."

**Comment by garethjones294** [comment]
Amendments made
