### ISSUE TITLE
Module_2/LAB_08_VNet Peering.md: Minor changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#165]
Module_2/LAB_08_VNet Peering.md: Minor changes:
--
Ex 1   Task 3 Step 2: "Select Create a resource > Compute > Windows Server 2016 Datacenter." should be "Select Create a resource >   Compute > Virtual Machine." 
(there is no Windows Server 2016 Datacenter under Compute)

Ex 1   Task 4 Step 2:  Double quote in middle of step should be removed.

**Comment by garethjones294** [comment]
Amendments made
