### ISSUE TITLE
Module_2/LAB_10_Load Balancer and App: Minor changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#166]
Module_2/LAB_10_Load Balancer and App: Minor changes:
--
Ex 1   Task 2 Step 2: "myBackendSubnet - for the subnet name." should be   under IP Addresses tab.
Ex 3   Task 1 Step 17: "select Create new" should be "select Add new"

**Comment by garethjones294** [comment]
Amendments made
