### ISSUE TITLE
Module_2/LAB_12_Azure Firewall.md: Minor changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#167]
Module_2/LAB_12_Azure Firewall.md:
--
The Azure Firewall service has been renamed to Firewalls:

Ex 1   Task 2 Step 1: "In the Azure portal, click All services and search for and select Azure Firewall." should be "In the Azure portal, click   All services and search for and select Firewalls."
Ex 1   Task 2 Step 2: "On the Firewall blade click Create firewall. "   should be "On the Firewalls   blade click Create firewall. "

Ex 1   Task 7 Step 7: The resources created in this lab are NOT needed for the next   lab so delete the resource group TEST-FW-RG.

**Comment by garethjones294** [comment]
Amendments made
