### ISSUE TITLE
Module_2/LAB_15_DDoS Protection.md: Minor changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#168]
Module_2/LAB_15_DDoS Protection.md: Minor changes:
--
(my bad, I listed the wrong tasks previously)
Ex 1   Task 1 Step 3: "Click Review + create, then click Create" should be   "Select Create"
Ex 1   Task 2 Step 3: "Click Create" should be "Click Review+Create, then click Create"

**Comment by garethjones294** [comment]
Amendments made
