### ISSUE TITLE
Module_2/LAB_06_NVA.md: Bold format

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-500-Azure-Security#169]
Module_2/LAB_06_NVA.md: Bold format:
--
Ex   1   Task 8 Step 1: **PUBLIC VM** should be in bold, and NETWORKING heading should not be in bold to be consistent with the rest of the table.

Thanks for taking care of all of these. It will certainly help the students get through the labs!

**Comment by garethjones294** [comment]
Amendments made
