### ISSUE TITLE
reduce manual typing for read-out of subscription id.

### ISSUE THREAD

**Issue by gro1m** [MicrosoftLearning/AZ-500-Azure-Security#176]
# Module: 01
#### Step: 02-03

Description of issue
Yeah, I think it would be nice to have here some kind of automation instead of manual copying:
```powershell
$sub_id = Get-AzSubscription | Select-Object -ExpandProperty Id | Out-String
$subScope = "/subscriptions/$sub_id"
```

**Comment by garethjones294** [comment]
Hi,

I agree automation would be useful here but if someone is using a login with multiple subscriptions then this could cause issues with the lab.

Regards
