### ISSUE TITLE
Create VNet VMs need to be in same VNet and Subnet

### ISSUE THREAD

**Issue by gro1m** [MicrosoftLearning/AZ-500-Azure-Security#177]
# Module: 02
#### Step: 01

Description of issue
For me it was not quite clear from the description that the settings in VM2 needed to use the same Virtual Network (and Subnet) in addition to using same diagnostic storage.

**Comment by azharkhuwaja** [comment]
Repeat steps 1 to 9 of task 2 in task 3.
