### ISSUE TITLE
Module 4 Lab 9 missing resources

### ISSUE THREAD

**Issue by dolsande** [MicrosoftLearning/AZ-500-Azure-Security#183]
# Module: 04
#### Step: 00

This demo references VMs that are created and destroyed back in module 2.

**Comment by azharkhuwaja** [comment]
Before task 1 of Exercise 1, you need to create 4 VMs to do this lab. The names of the VMs are myVM1, myVM2, Srv-Jump, and Srv-Work. First two VMs should be placed in Resource Group MyResourceGroup and other two in TEST-FW-RG.
