### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-500-Azure-Security#184]
# Module: 04
#### Step: 02

Description of issue
The perf query gives a syntax error
![Capture](https://user-images.githubusercontent.com/50480392/85020110-239a7500-b170-11ea-9a81-c08b7e1b8e0d.JPG)

Repro steps:

1.
1.
1.

**Comment by azharkhuwaja** [comment]
I have done this lab several times and there is no syntax error I received. I advise repeat steps, however, sql server has no logs so you won't be able to see any output.

**Comment by Franlusan** [comment]
I understand there are no logs to show but the message error should be different I think. it is very difficult to make syntax errors just typing "perf". I will do it again and see what happens.
