### ISSUE TITLE
Lab02 should be moved to appropriate module, does not belong to Mod 1

### ISSUE THREAD

**Issue by mtamayoo** [MicrosoftLearning/AZ-500-Azure-Security#28]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by garethjones294** [comment]
Hi, the module is correct.  There were several changes made in the December 2019 release which is available to MCTs via the Courseware Download Center.

**Comment by mtamayoo** [comment]
Thanks! I downloaded the MCT handbook early December and was not aware of the changes… than you because it was awful!
Any way I can contribute in the manuals as well? (I’m an MCT)

Regarding the Lab 2 in module 1, I insist, this lab is about SQL Always Encrypted functionality which is part of Module 3 in the December course layout.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AlexW134** [comment]
I agree! move that lab to Module 3
