### ISSUE TITLE
Members and guests can invite - guest deactivation missing

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-500-Azure-Security#55]
# Module: 04
#### Step: --

Description of issue

Members and guests can invite - Lab says to deactivate Member invites, but guest invite disabling is only mentioned in the headline, no steps are included in the lab to deactive guest invites.

Repro steps:

--

**Comment by garethjones294** [comment]
Lab guide amended

**Comment by derhoppe** [comment]
Guest users can invite should also be set to "no". Or is it security baseline to let your guests invite other guests?
