### ISSUE TITLE
Module 4 - Lab 08 - Exercise 2 - Task 3: Security Center instead of Cost Management + Billing

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-500-Azure-Security#56]
# Module: 04
## Lab/Demo: 08
####: Exercise 02
###### Step: 01

Description of issue

Should be "Security Center" instead of "Cost Management + Billing"

Repro steps:

--

**Comment by garethjones294** [comment]
Amended lab guides.
