### ISSUE TITLE
Instructional Updates Needed

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/AZ-500-Azure-Security#69]
The following code block entries have an additional space in them, which when pulled from this repository, causes the label of the code block to become part of the code block as shown below:

![image](https://user-images.githubusercontent.com/41710326/73963628-4bcabb00-48d6-11ea-9666-bc38c9e4005c.png)

They can be found in the following sections:

- Module 1 - Lab 2: Key Vault (Implementing Secure Data by setting up Always Encrypted) (all throughout this module)

- Module 1: Lab 6: Manage Identity and Access | Step 8 

-Module 02 (all throughout this module). 

- Module 3: Analyze audit logs and reports | Task 1 | Step 18
--note on this step as well: The commands as written doesn't work as the event hub name isn't unique enough. Instructions need to be tweaked to make the first powershell command use a unique name for the namespace. The second command then needs to reference that namespace.
-- step 20 (same section): Instructions   need to reference the unique name of the Event Hub namespace created in step   18.

- Module 3: Analyze audit logs and reports | Task 2 | Step 2 & 4

- Module 4: Lab 1 - Azure Monitor | Task 1 | Step 1

-Module 4: Lab 3 - Event hub | Task 5 | Step 1

-Module 4: Lab 3 - Event hub | Task 6 | Step 1

---Issues with the instructions---

Module 1 - Lab 2: Key Vault (Implementing Secure Data by setting up Always Encrypted) Formatting issue here that is including SQL due to spacing:

![image](https://user-images.githubusercontent.com/41710326/73965734-4d967d80-48da-11ea-8d24-61509404a50c.png)

- Module 2: Lab 7: Service Endpoints | Task 3 | Step 11 Table has been indented too far. 
 
![image](https://user-images.githubusercontent.com/41710326/73964282-86812300-48d7-11ea-90d0-cc0ad1278f89.png)

(this causes a  formatting break). 

-- Module 4: Lab 1 - Azure Monitor | Task 2 | Step 2 

Minor   Gui change, "Create" is now "Add"

-- Module 4: Lab 1 - Azure Monitor | Ex 1 | Task 4 | Step 2 
Minor   GUI change, need to click "Get Started" before the query editor   launches.  

-- Module 4: Lab 1 - Azure Monitor | Ex 2 | Task 4 | Step 2 
mistake   in instuctions. Should read 'Click on Logs (Analytics)'

Thank you for your help.

**Comment by ZekeStarr** [comment]
As per markdown spec, they should be indented once, or a total of 4 spaces, it looks like many of the trouble blocks here have 5 spaces before the opening fence.

https://github.github.com/gfm/#fenced-code-blocks 

While GitHub itself seems to handle the additional space in the fencing without issue, it doesn't fall in line with GitHub markdown spec. To produce an indented codeblock, 4 spaces are recommended.

**Comment by garethjones294** [comment]
These amendments have now been made.
