### ISSUE TITLE
Error message in Lab1

### ISSUE THREAD

**Issue by SlkRck** [MicrosoftLearning/AZ-500-Azure-Security#74]
# Module: 01
#### Step: 02

Description of issue
When you type the cmdlet "$domainObj = get-azureaddomain" you may get the error message:  Get-AzureADDomain: You must call the Connect-AzureAD cmdlet before calling any other cmdlets.

Repro steps:

1. type the cmdlet "$domainObj = get-azureaddomain"

The FIX:
1. Type the cmdlet "connect-azuread"

**Comment by garethjones294** [comment]
Addressed by adding the command and note indicating the command may be required in further labs.
