### ISSUE TITLE
Clarify unique key vault name in PowerShell command

### ISSUE THREAD

**Issue by simplescripter** [MicrosoftLearning/AZ-500-Azure-Security#76]
# Module: 01
#### Step: 04

Description of issue
Although the task states that the VaultName must be unique, the actual PowerShell code uses a hard-coded value of 'KeyVaultPS' for the vault name. For clarity, I suggest replacing the hard-coded value with replaceable tag, such as "<uniqueVaultName>" as follows:

New-AzKeyVault -VaultName '<uniqueVaultName>' -ResourceGroupName   'KeyVaultPSRG' -Location 'eastus'

**Comment by garethjones294** [comment]
Updated to include a note and placeholder for the Keyvault.
