### ISSUE TITLE
Should the resources be removed at the end of this lab?

### ISSUE THREAD

**Issue by simplescripter** [MicrosoftLearning/AZ-500-Azure-Security#86]
# Module: 02
#### Step: 10

Description of issue
Unlike other labs, this lab at the end states, "Leave all resources running. You will use them in a later lab." But when I search the AZ-500-Azure-Security repo for the resources created in this lab (for example, when I search for myVM1 and myVM2), the only later lab that references the Module 2 Lab 8 resources is Module 2 Lab 10. However, the Module 2 Lab 10 instructions call for re-creating those resources, not reusing previously provisioned resources. Unless I'm missing something, I suggest adding the same caveat to the end of this lab as all of the others: 

WARNING: Prior to continuing you should remove all resources used for this lab. To do this in the Azure Portal click Resource groups. Select any resources groups you have created. On the resource group blade click Delete Resource group, enter the Resource Group Name and click Delete. Repeat the process for any additional Resource Groups you may have created. Failure to do this may cause issues with other labs.

**Comment by garethjones294** [comment]
Amended
