### ISSUE TITLE
LAB_01_PIM updates

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-500-Azure-Security#88]
Lab_01_PIM.md
### Task 1:  Configure the Global Administrator role to require approval.
1.Click **Roles** and select **Global Administrator**.
  Click on **Role settings**
  Cick on **Edit**
1.  Scroll down and select **Require Approval to Activate** and  select your account as the approver then click **Select** then **Update**

### Task 2: Enable Isabella for Global Administrator privileges.

1.  Open **Azure AD Privileged Identity Management**.

1.  Click **Azure AD roles**.

1.  Click the **Quick Start** and select **Assign eligibility**.

1.  Select **Global Administrator**.
1.  Select **+ Add Member** and Click *Select a member** select **Isabella** and Click **Save** then Click **Add**.

**Comment by garethjones294** [comment]
Duplicate request.  Number is correct in preview.

**Comment by dpapkin** [comment]
Gareth,

Why did you close this so quickly?

I had several revisions and took the time to correct the outdated sections

Please reopen

David Papkin

**Comment by dpapkin** [comment]
> Duplicate request. Number is correct in preview.

What is this a duplicate request? I checked the preview issue before posting, this is updated.
