### ISSUE TITLE
md files line numbers are not sequential

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-500-Azure-Security#89]
I was teaching part of the MS Ninja team and a senior manager asked me why the Line numbers do not increment, the seem to be 1. 1. 1. 1.

Can we fix this please?

Thanks

David Papkin

For example Mod 1 PIM lab

### Task 2: Enable Isabella for Global Administrator privileges.

1.  Open **Azure AD Privileged Identity Management**.

1.  Click **Azure AD roles**.

1.  Click the **Quick Start** and select **Assign eligibility**.

     ![Screenshot](../Media/Module-1/ae3755ac-bd82-4e70-a102-ccbfc3aee48f.png)

1.  Select **Global Administrator** and click **Edit**.

1.  Select **+ Add Member** and Click *Select a member** select **Isabella** and Click **Save**.

1.  Open an in Private Browsing session and login to portal.azure.com as Isabella.

1.  Open **Azure AD Privileged Identity Management**.

1.  Select **My Roles**.

**Comment by garethjones294** [comment]
Hi David,

This is standard practice.  Please see a reference here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists 

Regards

**Comment by dpapkin** [comment]
Hi Gareth,

Thanks for  the reference, if I am asked again, I will quote the article.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
