### ISSUE TITLE
LAB_01_PIM errors

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-500-Azure-Security#90]
I am teaching this course tomorrow, I found some minor instruction drift. I am listing the items that need updating. I will update on any labs that I encounter this week

I have downloaded the latest LABS today.

Lab_01_PIM.md
### Task 1:  Configure the Global Administrator role to require approval.
1.Click **Roles** and select **Global Administrator**.
  Click on **Role settings**
  Cick on **Edit**
1.  Scroll down and select **Require Approval to Activate** and  select your account as the approver then click **Select** then **Update**

### Task 2: Enable Isabella for Global Administrator privileges.

1.  Select **Global Administrator**.
1.  Select **+ Add Member** and Click *Select a member** select **Isabella** and Click **Save** then Click **Add**

David Papkin
MCT

**Comment by garethjones294** [comment]
David,

I just see a copy of the lab instructions and no amendments.  Please do a pull request with suggested amendments for us to review.

Regards

**Comment by dpapkin** [comment]
Gareth,

I just did so, and reposted

I removed anything that has not changed. If there us a suggested format please let me know.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by garethjones294** [comment]
Hi David,

As I mentioned, please create a pull request so we can review fully and have a complete audit trail.

Regards

**Comment by dpapkin** [comment]
Hi Gareth,

Thanks!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by garethjones294** [comment]
Closing, no pull requests made.  Lab tested and still functions as expected.
