### ISSUE TITLE
Error working with Data Discovery & Classification

### ISSUE THREAD

**Issue by rexdekoning** [MicrosoftLearning/AZ-500-Azure-Security#91]
# Module: 03
#### Step: 01

Description of issue
The task describes to take the following step after setting up ADS:
To begin classifying your data, select the Classification tab at the top of the window.
But my Data Discovery & Classification keeps given Failed to Refresh data and when I click it it just says Error.

Repro steps:
Basically just follow to steps in the Lab

I've tried it with different accounts/roles in different subscriptions and on databases with or without data but I always get this error.

![Annotation 2020-03-13 133043](https://user-images.githubusercontent.com/8014683/76621111-f154f800-652e-11ea-8645-749d19114233.png)
![Annotation 2020-03-13 133111](https://user-images.githubusercontent.com/8014683/76621118-f5811580-652e-11ea-82db-de371c4e082f.png)

Vulnerability Assesment for example does work.

Kind regards, 

Rex de Koning

**Comment by kramit** [comment]
Unable to replicate issue, I have run the lab myself now and I get the data classification results. Maybe possible internal Azure issue? I ran this on the UK South region and there is no issue with the lab.

![image](https://user-images.githubusercontent.com/5239228/76681201-515ba500-65e8-11ea-9397-f09952ff8516.png)

**Comment by rexdekoning** [comment]
Thanks... I'll try again using that region to be sure. I've tried
westeurope and us-east. I'll update later today

Op za 14 mrt. 2020 12:39 schreef Michael Whitehouse <
notifications@github.com>:

**Comment by rexdekoning** [comment]
It's weird but if it's working for you it's probably something with my tenants... For me it still doesn't work. (Not only by using the labfiles but also when I create the sql server manually )  I'll close the issue for now and hope it will start working again.
