### ISSUE TITLE
Not able to connect VPN

### ISSUE THREAD

**Issue by karlochacon** [MicrosoftLearning/AZ-500-Azure-Security#92]
# Module: 02
#### Step: 00
On-Prem to Azure Connections - VPN Gateways and Tunnelling

Description of issue
I follow all steps and VPN shows as not connected

Repro steps:

guys I've followed the steps like 3 times now and still not getting this VPN showing as connected any idea?

I've created VPNs in Azure and my customers connect to it at least 15 times and I am following this lab in order to understand what my customer do in their side so I am more prepare

any idea why this is not connecting?

thanks

**Comment by garethjones294** [comment]
Hi

I have just completed the lab and its functioning as expected.  My VPN connected within a couple of minutes.

Regards

**Comment by karlochacon** [comment]
thanks a lot 
I followed these 2 and same issue

I will open a ticket with support so they can take a look at the logs

https://github.com/MicrosoftLearning/AZ-500-Azure-Security/blob/master/Instructions/Labs/Module_2/LAB_11_VPN%20Gateways%20and%20Tunnelling.md

https://community.sophos.com/kb/en-us/127546

**Comment by garethjones294** [comment]
Issue seems to be tired with Azure Pass subs restrictions.
