### ISSUE TITLE
Issue: Not able to deploy availability set with domain count 3

### ISSUE THREAD

**Issue by GhumanNavneet** [MicrosoftLearning/AZ-500-Azure-Security#98]
# Module: Module 2
#### Step: In your browser, navigate to the following URL to open the ARM template:

Description of issue
We are getting error while deploying the below ARM template:

```https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FGoDeploy%2FAZ300%2Fmaster%2Fxg-azure-master%2FmainTemplate.json```

Error Message: 
  "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"The specified fault domain count 3 must fall in the range 1 to 2.\",\r\n    \"target\": \"platformFaultDomainCount\"\r\n  }\r\n}"
                    }

Need to make change in below file of platformFaultDomainCount value to 2 or 1. It is not accepting 3.
https://github.com/godeploy/AZ300/blob/master/xg-azure-master/shared/availabilitySet-new.json

**Comment by garethjones294** [comment]
Hi,

This is due to the limitations as per Microsoft's announcements.  https://www.microsoft.com/en-us/learning/mocazurepass.aspx
